version: "3.5"
services:
  dev:
    container_name: template-dotnet-core-console-app-dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ".:/template-dotnet-core-console-app"
      - "./.aws:/root/.aws"
      - "./zshrc:/root/.zshrc"
      - template-dotnet-core-console-app-cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock

      # (find src* | grep  '/bin$' && find src* | grep  '/obj$' && find tests* | grep  '/bin$' && find tests* | grep  '/obj$')  | sed 's/^/ - \/template-dotnet-core-console-app\//'
      - /template-dotnet-core-console-app/src/TemplateDotnetCoreConsoleApp.Api/bin
      - /template-dotnet-core-console-app/src/TemplateDotnetCoreConsoleApp.Client/bin
      - /template-dotnet-core-console-app/src/TemplateDotnetCoreConsoleApp.Core/bin
      - /template-dotnet-core-console-app/src/TemplateDotnetCoreConsoleApp.Api/obj
      - /template-dotnet-core-console-app/src/TemplateDotnetCoreConsoleApp.Client/obj
      - /template-dotnet-core-console-app/src/TemplateDotnetCoreConsoleApp.Core/obj
      - /template-dotnet-core-console-app/tests/TemplateDotnetCoreConsoleApp.Api.Tests/bin
      - /template-dotnet-core-console-app/tests/TemplateDotnetCoreConsoleApp.Core.Tests/bin
      - /template-dotnet-core-console-app/tests/TemplateDotnetCoreConsoleApp.Api.Tests/obj
      - /template-dotnet-core-console-app/tests/TemplateDotnetCoreConsoleApp.Core.Tests/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - HISTFILE=/cache/.bash_history
    entrypoint: top -b
    logging:
      driver: none

volumes:
  template-dotnet-core-console-app-cache:
