version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./TemplateDotnetCoreConsoleApp.Cmd/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=test-local
    ports:
      - 5012:8080
